package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-05-11T16:46:44.134+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SW_GesauroRMSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SWGesauroRMSoap {

    /**
     * Reemisión de una colección de códigos de barras asociados a entradas directas de un número de operación
     */
    @WebMethod(operationName = "RMReemisionCodigosBarras", action = "http://tempuri.org/RMReemisionCodigosBarras")
    @RequestWrapper(localName = "RMReemisionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMReemisionCodigosBarras")
    @ResponseWrapper(localName = "RMReemisionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMReemisionCodigosBarrasResponse")
    @WebResult(name = "RMReemisionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TCodigosBarras rmReemisionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "numOperacion", targetNamespace = "http://tempuri.org/")
        long numOperacion
    );

    /**
     * Emisión de una colección de códigos de barras desactivados asociados a entradas directas en un mismo número de operación
     */
    @WebMethod(operationName = "RMEmisionCodigosBarrasDesactivados", action = "http://tempuri.org/RMEmisionCodigosBarrasDesactivados")
    @RequestWrapper(localName = "RMEmisionCodigosBarrasDesactivados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMEmisionCodigosBarrasDesactivados")
    @ResponseWrapper(localName = "RMEmisionCodigosBarrasDesactivadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMEmisionCodigosBarrasDesactivadosResponse")
    @WebResult(name = "RMEmisionCodigosBarrasDesactivadosResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TCodigosBarras rmEmisionCodigosBarrasDesactivados(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idConcepto", targetNamespace = "http://tempuri.org/")
        long idConcepto,
        @WebParam(name = "idTipoCliente", targetNamespace = "http://tempuri.org/")
        long idTipoCliente,
        @WebParam(name = "cantidad", targetNamespace = "http://tempuri.org/")
        int cantidad
    );

    /**
     * Comprobar si una entrada ya ha sido validada en el control de accesos
     */
    @WebMethod(operationName = "RMCodigoUsado", action = "http://tempuri.org/RMCodigoUsado")
    @RequestWrapper(localName = "RMCodigoUsado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCodigoUsado")
    @ResponseWrapper(localName = "RMCodigoUsadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCodigoUsadoResponse")
    @WebResult(name = "RMCodigoUsadoResult", targetNamespace = "http://tempuri.org/")
    public boolean rmCodigoUsado(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada
    );

    /**
     * Emisión de una colección de códigos de barras asociados a entradas directas en un mismo número de operación
     */
    @WebMethod(operationName = "RMEmisionCodigosBarras", action = "http://tempuri.org/RMEmisionCodigosBarras")
    @RequestWrapper(localName = "RMEmisionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMEmisionCodigosBarras")
    @ResponseWrapper(localName = "RMEmisionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMEmisionCodigosBarrasResponse")
    @WebResult(name = "RMEmisionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.TCodigosBarras rmEmisionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "")
        long idEntidad,
        @WebParam(name = "idConcepto", targetNamespace = "")
        long idConcepto,
        @WebParam(name = "idTipoCliente", targetNamespace = "")
        long idTipoCliente,
        @WebParam(name = "cantidad", targetNamespace = "")
        int cantidad
    );

    /**
     * Desactivación de códigos de entradas directas
     */
    @WebMethod(operationName = "RMDesactivarEntrada", action = "http://tempuri.org/RMDesactivarEntrada")
    @RequestWrapper(localName = "RMDesactivarEntrada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMDesactivarEntrada")
    @ResponseWrapper(localName = "RMDesactivarEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMDesactivarEntradaResponse")
    @WebResult(name = "RMDesactivarEntradaResult", targetNamespace = "http://tempuri.org/")
    public boolean rmDesactivarEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada
    );

    /**
     * Activación de códigos de entradas directas
     */
    @WebMethod(operationName = "RMActivarEntrada", action = "http://tempuri.org/RMActivarEntrada")
    @RequestWrapper(localName = "RMActivarEntrada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMActivarEntrada")
    @ResponseWrapper(localName = "RMActivarEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMActivarEntradaResponse")
    @WebResult(name = "RMActivarEntradaResult", targetNamespace = "http://tempuri.org/")
    public boolean rmActivarEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada
    );

    /**
     * Cancelación de un conjunto de entradas directas que se han emitido a través de solicitud de códigos de barras para la entidad pasada por parámetro y que no han sido utilizados
     */
    @WebMethod(operationName = "RMCancelacionCodigosBarras", action = "http://tempuri.org/RMCancelacionCodigosBarras")
    @RequestWrapper(localName = "RMCancelacionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCancelacionCodigosBarras")
    @ResponseWrapper(localName = "RMCancelacionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCancelacionCodigosBarrasResponse")
    @WebResult(name = "RMCancelacionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    public boolean rmCancelacionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "numOperacion", targetNamespace = "http://tempuri.org/")
        long numOperacion
    );

    /**
     * Cancelación de una única entrada directa que se han emitido a través de solicitud de códigos de barras para la entidad pasada por parámetro y que no han sido utilizados
     */
    @WebMethod(operationName = "RMCancelacionEntrada", action = "http://tempuri.org/RMCancelacionEntrada")
    @RequestWrapper(localName = "RMCancelacionEntrada", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCancelacionEntrada")
    @ResponseWrapper(localName = "RMCancelacionEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RMCancelacionEntradaResponse")
    @WebResult(name = "RMCancelacionEntradaResult", targetNamespace = "http://tempuri.org/")
    public boolean rmCancelacionEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada
    );
}
