
package com.epl.rmadrid.xto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SW_GesauroRMSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SWGesauroRMSoap {


    /**
     * Emisi�n de una colecci�n de c�digos de barras asociados a entradas directas en un mismo n�mero de operaci�n
     * 
     * @param idEntidad
     * @param authHeader
     * @param idConcepto
     * @param idTipoCliente
     * @param cantidad
     * @return
     *     returns org.rm.TCodigosBarras
     */
    @WebMethod(operationName = "RMEmisionCodigosBarras", action = "http://tempuri.org/RMEmisionCodigosBarras")
    @WebResult(name = "RMEmisionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMEmisionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.rm.RMEmisionCodigosBarras")
    @ResponseWrapper(localName = "RMEmisionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMEmisionCodigosBarrasResponse")
    public TCodigosBarras rmEmisionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idConcepto", targetNamespace = "http://tempuri.org/")
        long idConcepto,
        @WebParam(name = "idTipoCliente", targetNamespace = "http://tempuri.org/")
        long idTipoCliente,
        @WebParam(name = "cantidad", targetNamespace = "http://tempuri.org/")
        int cantidad,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Emisi�n de una colecci�n de c�digos de barras desactivados asociados a entradas directas en un mismo n�mero de operaci�n
     * 
     * @param idEntidad
     * @param authHeader
     * @param idConcepto
     * @param idTipoCliente
     * @param cantidad
     * @return
     *     returns org.rm.TCodigosBarras
     */
    @WebMethod(operationName = "RMEmisionCodigosBarrasDesactivados", action = "http://tempuri.org/RMEmisionCodigosBarrasDesactivados")
    @WebResult(name = "RMEmisionCodigosBarrasDesactivadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMEmisionCodigosBarrasDesactivados", targetNamespace = "http://tempuri.org/", className = "org.rm.RMEmisionCodigosBarrasDesactivados")
    @ResponseWrapper(localName = "RMEmisionCodigosBarrasDesactivadosResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMEmisionCodigosBarrasDesactivadosResponse")
    public TCodigosBarras rmEmisionCodigosBarrasDesactivados(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idConcepto", targetNamespace = "http://tempuri.org/")
        long idConcepto,
        @WebParam(name = "idTipoCliente", targetNamespace = "http://tempuri.org/")
        long idTipoCliente,
        @WebParam(name = "cantidad", targetNamespace = "http://tempuri.org/")
        int cantidad,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Reemisi�n de una colecci�n de c�digos de barras asociados a entradas directas de un n�mero de operaci�n
     * 
     * @param idEntidad
     * @param authHeader
     * @param numOperacion
     * @return
     *     returns org.rm.TCodigosBarras
     */
    @WebMethod(operationName = "RMReemisionCodigosBarras", action = "http://tempuri.org/RMReemisionCodigosBarras")
    @WebResult(name = "RMReemisionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMReemisionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.rm.RMReemisionCodigosBarras")
    @ResponseWrapper(localName = "RMReemisionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMReemisionCodigosBarrasResponse")
    public TCodigosBarras rmReemisionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "numOperacion", targetNamespace = "http://tempuri.org/")
        long numOperacion,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Cancelaci�n de un conjunto de entradas directas que se han emitido a trav�s de solicitud de c�digos de barras para la entidad pasada por par�metro y que no han sido utilizados
     * 
     * @param idEntidad
     * @param authHeader
     * @param numOperacion
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RMCancelacionCodigosBarras", action = "http://tempuri.org/RMCancelacionCodigosBarras")
    @WebResult(name = "RMCancelacionCodigosBarrasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMCancelacionCodigosBarras", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCancelacionCodigosBarras")
    @ResponseWrapper(localName = "RMCancelacionCodigosBarrasResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCancelacionCodigosBarrasResponse")
    public boolean rmCancelacionCodigosBarras(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "numOperacion", targetNamespace = "http://tempuri.org/")
        long numOperacion,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Cancelaci�n de una �nica entrada directa que se han emitido a trav�s de solicitud de c�digos de barras para la entidad pasada por par�metro y que no han sido utilizados
     * 
     * @param idEntidad
     * @param authHeader
     * @param idEntrada
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RMCancelacionEntrada", action = "http://tempuri.org/RMCancelacionEntrada")
    @WebResult(name = "RMCancelacionEntradaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMCancelacionEntrada", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCancelacionEntrada")
    @ResponseWrapper(localName = "RMCancelacionEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCancelacionEntradaResponse")
    public boolean rmCancelacionEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Activaci�n de c�digos de entradas directas
     * 
     * @param idEntidad
     * @param authHeader
     * @param idEntrada
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RMActivarEntrada", action = "http://tempuri.org/RMActivarEntrada")
    @WebResult(name = "RMActivarEntradaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMActivarEntrada", targetNamespace = "http://tempuri.org/", className = "org.rm.RMActivarEntrada")
    @ResponseWrapper(localName = "RMActivarEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMActivarEntradaResponse")
    public boolean rmActivarEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Desactivaci�n de c�digos de entradas directas
     * 
     * @param idEntidad
     * @param authHeader
     * @param idEntrada
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RMDesactivarEntrada", action = "http://tempuri.org/RMDesactivarEntrada")
    @WebResult(name = "RMDesactivarEntradaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMDesactivarEntrada", targetNamespace = "http://tempuri.org/", className = "org.rm.RMDesactivarEntrada")
    @ResponseWrapper(localName = "RMDesactivarEntradaResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMDesactivarEntradaResponse")
    public boolean rmDesactivarEntrada(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Comprobar si una entrada ya ha sido validada en el control de accesos
     * 
     * @param idEntidad
     * @param authHeader
     * @param idEntrada
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RMCodigoUsado", action = "http://tempuri.org/RMCodigoUsado")
    @WebResult(name = "RMCodigoUsadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMCodigoUsado", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCodigoUsado")
    @ResponseWrapper(localName = "RMCodigoUsadoResponse", targetNamespace = "http://tempuri.org/", className = "org.rm.RMCodigoUsadoResponse")
    public boolean rmCodigoUsado(
        @WebParam(name = "idEntidad", targetNamespace = "http://tempuri.org/")
        long idEntidad,
        @WebParam(name = "idEntrada", targetNamespace = "http://tempuri.org/")
        long idEntrada,
        @WebParam(name = "AuthHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

}
