
package org.rm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-05-09T15:37:47.623+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class SWGesauroRMSoap_SWGesauroRMSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "SW_GesauroRM");

    private SWGesauroRMSoap_SWGesauroRMSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SWGesauroRM.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SWGesauroRM ss = new SWGesauroRM(wsdlURL, SERVICE_NAME);
        SWGesauroRMSoap port = ss.getSWGesauroRMSoap12();  
        
        {
        System.out.println("Invoking rmReemisionCodigosBarras...");
        long _rmReemisionCodigosBarras_idEntidad = 6326025872730263647l;
        long _rmReemisionCodigosBarras_numOperacion = -2483099634757079008l;
        org.rm.TCodigosBarras _rmReemisionCodigosBarras__return = port.rmReemisionCodigosBarras(_rmReemisionCodigosBarras_idEntidad, _rmReemisionCodigosBarras_numOperacion);
        System.out.println("rmReemisionCodigosBarras.result=" + _rmReemisionCodigosBarras__return);


        }
        {
        System.out.println("Invoking rmEmisionCodigosBarrasDesactivados...");
        long _rmEmisionCodigosBarrasDesactivados_idEntidad = -2020677038379020325l;
        long _rmEmisionCodigosBarrasDesactivados_idConcepto = -4840305238790471360l;
        long _rmEmisionCodigosBarrasDesactivados_idTipoCliente = -6701053306946691236l;
        int _rmEmisionCodigosBarrasDesactivados_cantidad = 269530158;
        org.rm.TCodigosBarras _rmEmisionCodigosBarrasDesactivados__return = port.rmEmisionCodigosBarrasDesactivados(_rmEmisionCodigosBarrasDesactivados_idEntidad, _rmEmisionCodigosBarrasDesactivados_idConcepto, _rmEmisionCodigosBarrasDesactivados_idTipoCliente, _rmEmisionCodigosBarrasDesactivados_cantidad);
        System.out.println("rmEmisionCodigosBarrasDesactivados.result=" + _rmEmisionCodigosBarrasDesactivados__return);


        }
        {
        System.out.println("Invoking rmCodigoUsado...");
        long _rmCodigoUsado_idEntidad = 46917176222627212l;
        long _rmCodigoUsado_idEntrada = -5873685956407433992l;
        boolean _rmCodigoUsado__return = port.rmCodigoUsado(_rmCodigoUsado_idEntidad, _rmCodigoUsado_idEntrada);
        System.out.println("rmCodigoUsado.result=" + _rmCodigoUsado__return);


        }
        {
        System.out.println("Invoking rmEmisionCodigosBarras...");
        long _rmEmisionCodigosBarras_idEntidad = 6809507230376631807l;
        long _rmEmisionCodigosBarras_idConcepto = 184239264657385457l;
        long _rmEmisionCodigosBarras_idTipoCliente = -2627178233480540775l;
        int _rmEmisionCodigosBarras_cantidad = -1386563469;
        org.rm.TCodigosBarras _rmEmisionCodigosBarras__return = port.rmEmisionCodigosBarras(_rmEmisionCodigosBarras_idEntidad, _rmEmisionCodigosBarras_idConcepto, _rmEmisionCodigosBarras_idTipoCliente, _rmEmisionCodigosBarras_cantidad);
        System.out.println("rmEmisionCodigosBarras.result=" + _rmEmisionCodigosBarras__return);


        }
        {
        System.out.println("Invoking rmDesactivarEntrada...");
        long _rmDesactivarEntrada_idEntidad = -1628944722474037796l;
        long _rmDesactivarEntrada_idEntrada = 5869595113893317796l;
        boolean _rmDesactivarEntrada__return = port.rmDesactivarEntrada(_rmDesactivarEntrada_idEntidad, _rmDesactivarEntrada_idEntrada);
        System.out.println("rmDesactivarEntrada.result=" + _rmDesactivarEntrada__return);


        }
        {
        System.out.println("Invoking rmActivarEntrada...");
        long _rmActivarEntrada_idEntidad = -2016267502942984670l;
        long _rmActivarEntrada_idEntrada = 2740313000159593530l;
        boolean _rmActivarEntrada__return = port.rmActivarEntrada(_rmActivarEntrada_idEntidad, _rmActivarEntrada_idEntrada);
        System.out.println("rmActivarEntrada.result=" + _rmActivarEntrada__return);


        }
        {
        System.out.println("Invoking rmCancelacionCodigosBarras...");
        long _rmCancelacionCodigosBarras_idEntidad = 1815665142188808334l;
        long _rmCancelacionCodigosBarras_numOperacion = -8470262592420968815l;
        boolean _rmCancelacionCodigosBarras__return = port.rmCancelacionCodigosBarras(_rmCancelacionCodigosBarras_idEntidad, _rmCancelacionCodigosBarras_numOperacion);
        System.out.println("rmCancelacionCodigosBarras.result=" + _rmCancelacionCodigosBarras__return);


        }
        {
        System.out.println("Invoking rmCancelacionEntrada...");
        long _rmCancelacionEntrada_idEntidad = -5775459655815624039l;
        long _rmCancelacionEntrada_idEntrada = 8531098483060928602l;
        boolean _rmCancelacionEntrada__return = port.rmCancelacionEntrada(_rmCancelacionEntrada_idEntidad, _rmCancelacionEntrada_idEntrada);
        System.out.println("rmCancelacionEntrada.result=" + _rmCancelacionEntrada__return);


        }

        System.exit(0);
    }

}
