
package org.rm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SW_GesauroRM", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/desar/workspace/rmadrid2/wsdl/rm.wsdl")
public class SWGesauroRM
    extends Service
{

    private final static URL SWGESAURORM_WSDL_LOCATION;
    private final static WebServiceException SWGESAURORM_EXCEPTION;
    private final static QName SWGESAURORM_QNAME = new QName("http://tempuri.org/", "SW_GesauroRM");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/desar/workspace/rmadrid2/wsdl/rm.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SWGESAURORM_WSDL_LOCATION = url;
        SWGESAURORM_EXCEPTION = e;
    }

    public SWGesauroRM() {
        super(__getWsdlLocation(), SWGESAURORM_QNAME);
    }

    public SWGesauroRM(WebServiceFeature... features) {
        super(__getWsdlLocation(), SWGESAURORM_QNAME, features);
    }

    public SWGesauroRM(URL wsdlLocation) {
        super(wsdlLocation, SWGESAURORM_QNAME);
    }

    public SWGesauroRM(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SWGESAURORM_QNAME, features);
    }

    public SWGesauroRM(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SWGesauroRM(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SWGesauroRMSoap
     */
    @WebEndpoint(name = "SW_GesauroRMSoap")
    public SWGesauroRMSoap getSWGesauroRMSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SW_GesauroRMSoap"), SWGesauroRMSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SWGesauroRMSoap
     */
    @WebEndpoint(name = "SW_GesauroRMSoap")
    public SWGesauroRMSoap getSWGesauroRMSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SW_GesauroRMSoap"), SWGesauroRMSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SWGESAURORM_EXCEPTION!= null) {
            throw SWGESAURORM_EXCEPTION;
        }
        return SWGESAURORM_WSDL_LOCATION;
    }

}
